// A list of all actions in the system.
export default {
  STARTUP: 'STARTUP',

  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SET_APP_PROPS: 'SET_APP_PROPS',
  TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',
  GET_USE: 'GET_USE',
  EDIT_USER: 'EDIT_USER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
};
